### ISSUE TITLE
The latest files are not moved

### ISSUE THREAD

**Issue by hightower5** [uptoratlen/gsArchivPDFDownloader#1]
Hello uptoratlen,

thanks for this little fine tool. The readme.md is very well written. So that a beginner is able to run this tool.

I have stopped the download at 2017. After a new start of the tool the files from 2018-2020 wasn't moved to the sub folders.
And the new one have another format like: "GameStar Nr. 1_1998.pdf". Perhaps it is possible to add a leading zero to the files for the months "Jan-Sep". I would prefer the format "GameStar Nr._01_1998.pdf"
And there was a problem with some files. It seems that delayed downloads are not moved to a sub folder of the year.
Error message:
`2021-03-10 01:16:47 PM:[INFO ]  Try now download of : Jahr 2016 and Ausgabe 1
2021-03-10 01:17:26 PM:[WARNI]  Download still in progress - may need recheck - aborting wait to continue - may complete in background
2021-03-10 01:17:26 PM:[WARNI]  Download not yet completed - not possible to move by now`

Is it very complicated to add code for the missing PDFs from 1997 (as there are only 4), from 2021 (as there are only 4) and  the 2013/13 edition ? 

I hope you can fix the problem.

Best regards

Hightower

**Comment by uptoratlen** [comment]
I found out that after my mail "they" did someting on 2017/10 (the 20 year edition), and now the "blätterkatalog" doe snot open anymore. I will add a exception to prevent download of 2017/10 (later it will be added). That will fix the issue with 2017 and later also. 

And I will do the same for the "special" years 1997 and 2021. I will do it in a configurable way. Not yet clear how, but I think the gs.json will the way to define exclusions and inclusions.

The filename with a leading zero on the edition. Yes, good idea as windows sorts it in a not so nice way. I will add also a option for this.

And thx for the feedback.

**Comment by uptoratlen** [comment]
@hightower5 
I checked the state of the script vs the server at 11 March 2021 ~ 19:00 (local German time) and I agreed with all you mentioned. I fixed it and enhanced the script, so you might give it a try? Feel free to report back if that solved some of your issues. I admit I did not run a full e2e test cycle. I run some preliminary tests for certain years. Nice that my playground for all this at least helped someone 👍  If you report back we could close this issue.

**Comment by uptoratlen** [comment]
@hightower5 
Please check if you like. The account is unflagged. release or code is now open again.

**Comment by hightower5** [comment]
@uptoratlen 

Thank you. The version 0.2 solves this problem.

**Comment by uptoratlen** [comment]
Thx for the feedback
