### ISSUE TITLE
2017 / 10 - fixed on server [No issue] 😉 

### ISSUE THREAD

**Issue by hightower5** [uptoratlen/gsArchivPDFDownloader#10]
The error of the edition 2017/10 was fixed! 😊 

Best regards

Hightower

**Comment by uptoratlen** [comment]
Cool, I also tested it, works now.
I guess your gs.json looks like this:
`       ....
 "skip_editions": [
        ]
....
`
right?

**Comment by hightower5** [comment]
I have written a request to the support and got the answer that they will take care of it. That's why I have checked that the last few days.
