### ISSUE TITLE
Define somehow download Job for next release

### ISSUE THREAD

**Issue by hightower5** [uptoratlen/gsArchivPDFDownloader#2]
Hello @uptoratlen

I like the new version. Especially the editing options. By testing the release 0.2 I noticed that a function is missing. 
It would be very nice, when the user could specify the year or a time period of the downloaded magazines.

A nice to have feature for version 0.3 ;)

Best regards

Hightower5

**Comment by uptoratlen** [comment]
@hightower5 
I hope the method fits your need or request. I kept the definition in the JSON file, as it is a bit of flexible. Currently there is no UI and command line would be complicated (arguments). Maybe you would like to take a short look. And to be honest, again by moving the download to a separate function I almost was about to do it in v0.2, but again I was a bit of too lazy :-)
Feedback would be nice. Thx for your input.

**Comment by hightower5** [comment]
@uptoratlen 
I like the new version 0.3. Editing the "gs.json" file is not comfortable but functional.  ;-)
Thanks for it!
---
I thought about a small improvement. Does python allow arguments?

Perhaps it is possible to use the script with the default gs.json and additional arguments. 
E.g.  To start the download of the complete year "2019"

`python gsArchivPDFDownloader.py 2019`

**Comment by uptoratlen** [comment]
- Accepted by OP. Second RFC referenced in new issue.
