### ISSUE TITLE
Add comandline to download a year

### ISSUE THREAD

**Issue by uptoratlen** [uptoratlen/gsArchivPDFDownloader#3]
Use the script with the default gs.json and additional arguments. 
E.g.  To start the download of the complete year "2019"

`python gsArchivPDFDownloader.py 2019`

_Originally posted by @hightower5 in https://github.com/uptoratlen/gsArchivPDFDownloader/issues/2#issuecomment-799004616_

**Comment by uptoratlen** [comment]
@hightower5
I just added a new version of the .py file. The command line is optional added, check the readme.
I modified your suggestion of `python gsArchivPDFDownloader.py 2019`  to 
`python gsArchivPDFDownloader.py -y 2019` or `python gsArchivPDFDownloader.py --year 2019`

Maybe you want to check and report back if that satisfies your need. Of course the previous features are still active so you got both.

**Comment by hightower5** [comment]
Thank you for the new command line option. First I was irritated of the word "range" in the help. I thought I could also choose an archive range like "1998-2000". My fault. The input of year must be in the range from 1997-2035. ;-)

The error website "Fehler - Die Seite konnte nicht gefunden werden." is a bit disturbing.

**Comment by uptoratlen** [comment]
Closed as accepted.
The page (not found) is as a invalid url is requested. As mentioned I will add a nicer way maybe next time.

**Comment by hightower5** [comment]
> Closed as accepted.
> The page (not found) is as a invalid url is requested. As mentioned I will add a nicer way maybe next time.

Hello,
I hope, that you would fix this in a new version. :(
Maybe you can still fix the error.

Best regards

hightower
