### ISSUE TITLE
Problem with Editions / Download does not stop on edited edition in gs.json file

### ISSUE THREAD

**Issue by hightower5** [uptoratlen/gsArchivPDFDownloader#7]
### Editions in gs.json

I've found a new problem. The download of "editions" doesn't work anymore. 

[https://github.com/uptoratlen/gsArchivPDFDownloader#editions-in-gsjson](url)

I've tried the following argument and setting: 

python gsArchivPDFDownloader.py -y 2020

Setting:       
 ```
"editions": [
            {
                "1997": "9,10,11,12"
            },
            {
                "1998": "1,2,3,4,5,6,7,8,9,10,11,12"
            },
            ...
            {
                "2019": "1,2,3,4,5,6,7,8,9,10,11,12"
            },
            {
                "2020": "1,2,3,4"
            },
            {
                "2021": "1,2,3,4,5"
            }
        ]
    }
]
```
The download doesn't stop after the edition "4".

**Comment by uptoratlen** [comment]
Oh, I see. the -y/--year xxxx does not trigger a "edition" run. The "year" run overwrites the editions.
I see it also a bit of confusing. 
The original idea was to download all editions in one job (like a new user to "Gs plus"), than we came up with the idea to download certain years (full) and the option to download a range.
So thinking of that it might be best to rethink the idea and do something like this:

> gsArchivPDFDownloader.py = help / version / no run
> gsArchivPDFDownloader.py -l = latest edition based on gs.json + 1
> gsArchivPDFDownloader.py -f  = full download from 1997 to current Month +1 (today run would try up to 2021/06)
> gsArchivPDFDownloader.py -y yyyy  = full download for year xxxx with limitation current year only current month +1 and 1997  starting from 9)
> gsArchivPDFDownloader.py -r yyyy:mm-yyyy:mm = range download for year/month to year/month; like -r 1997:07-2002:12

So we could get rid of the edition section of the gs.json and it might be more intuitive?
Take this as a proposal and let me have your thoughts on it. 
If a program is not matching the user xp expected it needs to be changed, even there might be some developer concerns (thinking of what might go wrong this time...)

**Comment by hightower5** [comment]
Ok, my fault. I forgot that it is possible to use the script without an argument. ;)
But I like your idea, this would be much more comfortable.

**Comment by uptoratlen** [comment]
So, I take this as a "go". In addition I will move the credentials to a extra file. So it is maybe easier to test new versions without editing always the passwords in, in case the config change.

**Comment by uptoratlen** [comment]
I gave my best. v0.6 (not yet in the release) is online. Please have a look. 
A full run on all options was done (automatic), but I guess you will find a bug anyway :-)

You will notice some drastic changes in the code. But the main task should be the same. Keep an eye also on the new comandline args "--range" and "--full"

v0.6 also contains a wider range of input check.

**Comment by hightower5** [comment]
I wanted to say: "Well, I will do my very best." 😏 But I didn't find a problem.

OK, one thing. The arguments are case-sensitivity, so I would like, that "version" also use a small character. -> -v

Thank you for, I would say, the best version.

**Comment by uptoratlen** [comment]
Thx, the "-v" will be done in a small release after this.

**Comment by hightower5** [comment]
Thank you for the update 0.6.1.
